-- Truncate the ingredients table (cascade to remove dependencies)
TRUNCATE TABLE public.ingredients CASCADE;

-- Insert new ingredients
INSERT INTO public.ingredients (name, category, image_url, synonyms) VALUES
('ail', 'fruits_legumes', 'https://iqauznwytxtpslyflmvv.supabase.co/storage/v1/object/public/ingredient-images/ail.jpg', ARRAY['gousse', 'persillade', 'condiment', 'ails']),
('baguette', 'autre', 'https://iqauznwytxtpslyflmvv.supabase.co/storage/v1/object/public/ingredient-images/baguette.jpg', ARRAY['pain', 'tradition', 'baguettes', 'boulangerie']),
('banane', 'fruits_legumes', 'https://iqauznwytxtpslyflmvv.supabase.co/storage/v1/object/public/ingredient-images/banane.jpg', ARRAY['fruit', 'jaune', 'dessert']),
('beurre', 'produits_laitiers', 'https://iqauznwytxtpslyflmvv.supabase.co/storage/v1/object/public/ingredient-images/beurre.jpg', ARRAY['doux', 'demi-sel', 'gras', 'tartine', 'cuisson']),
('boeuf', 'boucherie', 'https://iqauznwytxtpslyflmvv.supabase.co/storage/v1/object/public/ingredient-images/boeuf.jpg', ARRAY['steak', 'hache', 'burger', 'viande', 'rouge']),
('brocoli', 'fruits_legumes', 'https://iqauznwytxtpslyflmvv.supabase.co/storage/v1/object/public/ingredient-images/brocolis.jpg', ARRAY['chou', 'vert', 'fleurette']),
('carotte', 'fruits_legumes', 'https://iqauznwytxtpslyflmvv.supabase.co/storage/v1/object/public/ingredient-images/carottes.jpg', ARRAY['rapee', 'orange', 'legume']),
('chocolat', 'epicerie_sucree', 'https://iqauznwytxtpslyflmvv.supabase.co/storage/v1/object/public/ingredient-images/chocolat.jpg', ARRAY['noir', 'lait', 'blanc', 'cacao', 'dessert', 'tablette']),
('citron', 'fruits_legumes', 'https://iqauznwytxtpslyflmvv.supabase.co/storage/v1/object/public/ingredient-images/citron.jpg', ARRAY['jaune', 'vert', 'jus', 'zeste', 'agrume']),
('cornichon', 'epicerie_salee', 'https://iqauznwytxtpslyflmvv.supabase.co/storage/v1/object/public/ingredient-images/cornichons.jpg', ARRAY['bocal', 'vinaigre', 'maille', 'croquant']),
('courgette', 'fruits_legumes', 'https://iqauznwytxtpslyflmvv.supabase.co/storage/v1/object/public/ingredient-images/courgette.jpg', ARRAY['legume', 'vert', 'gratin']),
('farine', 'epicerie_salee', 'https://iqauznwytxtpslyflmvv.supabase.co/storage/v1/object/public/ingredient-images/farine.jpg', ARRAY['ble', 'maizena', 'gateau', 'poudre', 't45', 't55']),
('fraise', 'fruits_legumes', 'https://iqauznwytxtpslyflmvv.supabase.co/storage/v1/object/public/ingredient-images/fraise.jpg', ARRAY['tagada', 'charlotte', 'rouge', 'gariguette', 'fruit']),
('framboise', 'fruits_legumes', 'https://iqauznwytxtpslyflmvv.supabase.co/storage/v1/object/public/ingredient-images/framboises.jpg', ARRAY['coulis', 'confiture', 'rouge', 'fruit']),
('fromage', 'produits_laitiers', 'https://iqauznwytxtpslyflmvv.supabase.co/storage/v1/object/public/ingredient-images/fromage.jpg', ARRAY['camembert', 'brie', 'comte', 'emmental', 'vache qui rit', 'raclette', 'chevre', 'roquefort']),
('gingembre', 'fruits_legumes', 'https://iqauznwytxtpslyflmvv.supabase.co/storage/v1/object/public/ingredient-images/gingembre.jpg', ARRAY['sushi', 'racine', 'epice', 'confit']),
('huile', 'epicerie_salee', 'https://iqauznwytxtpslyflmvv.supabase.co/storage/v1/object/public/ingredient-images/huile.jpg', ARRAY['olive', 'tournesol', 'friture', 'isio4', 'colza', 'noix', 'sesame']),
('lait', 'produits_laitiers', 'https://iqauznwytxtpslyflmvv.supabase.co/storage/v1/object/public/ingredient-images/lait.jpg', ARRAY['creme', 'lactose', 'vacheresse', 'soja', 'amande', 'avoine', 'entier', 'demi-ecreme']),
('lard', 'boucherie', 'https://iqauznwytxtpslyflmvv.supabase.co/storage/v1/object/public/ingredient-images/lard.jpg', ARRAY['lardon', 'bacon', 'cochon', 'fume', 'poitrine']),
('lentille', 'epicerie_salee', 'https://iqauznwytxtpslyflmvv.supabase.co/storage/v1/object/public/ingredient-images/lentilles.jpg', ARRAY['saucisse', 'petit sale', 'vertes', 'corail', 'beluga', 'conserve']),
('mais', 'epicerie_salee', 'https://iqauznwytxtpslyflmvv.supabase.co/storage/v1/object/public/ingredient-images/mais.jpg', ARRAY['pop corn', 'geant vert', 'conserve', 'grain', 'epis']),
('mangue', 'fruits_legumes', 'https://iqauznwytxtpslyflmvv.supabase.co/storage/v1/object/public/ingredient-images/mangue.jpg', ARRAY['exotique', 'chutney', 'jaune', 'fruit']),
('menthe', 'fruits_legumes', 'https://iqauznwytxtpslyflmvv.supabase.co/storage/v1/object/public/ingredient-images/menthe.jpg', ARRAY['mojito', 'the', 'sirop', 'feuille', 'fraiche']),
('noix', 'fruits_legumes', 'https://iqauznwytxtpslyflmvv.supabase.co/storage/v1/object/public/ingredient-images/noix.jpg', ARRAY['cajou', 'pecan', 'apero', 'grenoble', 'macadamia', 'noisette']),
('oeuf', 'produits_frais', 'https://iqauznwytxtpslyflmvv.supabase.co/storage/v1/object/public/ingredient-images/oeufs.jpg', ARRAY['omelette', 'coque', 'dur', 'mimosa', 'blanc', 'jaune', 'poule']),
('oignon', 'fruits_legumes', 'https://iqauznwytxtpslyflmvv.supabase.co/storage/v1/object/public/ingredient-images/oignon.jpg', ARRAY['echalote', 'ail', 'rouge', 'jaune', 'blanc', 'botte']),
('orange', 'fruits_legumes', 'https://iqauznwytxtpslyflmvv.supabase.co/storage/v1/object/public/ingredient-images/orange.jpg', ARRAY['jus', 'vitamine', 'agrume', 'clementine', 'mandarine']),
('pain', 'autre', 'https://iqauznwytxtpslyflmvv.supabase.co/storage/v1/object/public/ingredient-images/pain.jpg', ARRAY['baguette', 'boule', 'mie', 'sandwich', 'tartine', 'complet', 'cereales']),
('piment', 'epicerie_salee', 'https://iqauznwytxtpslyflmvv.supabase.co/storage/v1/object/public/ingredient-images/piment.jpg', ARRAY['tabasco', 'harissa', 'fort', 'epice', 'espelette', 'cayenne']),
('poisson', 'poissonnerie', 'https://iqauznwytxtpslyflmvv.supabase.co/storage/v1/object/public/ingredient-images/poisson.jpg', ARRAY['colin', 'cabillaud', 'pane', 'captain iglo', 'merlu', 'bar', 'dorade']),
('poivron', 'fruits_legumes', 'https://iqauznwytxtpslyflmvv.supabase.co/storage/v1/object/public/ingredient-images/poivrons.jpg', ARRAY['piment doux', 'tricolore', 'rouge', 'vert', 'jaune']),
('pomme de terre', 'fruits_legumes', 'https://iqauznwytxtpslyflmvv.supabase.co/storage/v1/object/public/ingredient-images/pomme-de-terre.jpg', ARRAY['frite', 'puree', 'chips', 'lays', 'patate', 'vapeur', 'sautées']),
('porc', 'boucherie', 'https://iqauznwytxtpslyflmvv.supabase.co/storage/v1/object/public/ingredient-images/porc.jpg', ARRAY['cotelette', 'roti', 'jambon', 'cochon', 'filet mignon']),
('poulet', 'boucherie', 'https://iqauznwytxtpslyflmvv.supabase.co/storage/v1/object/public/ingredient-images/poulet.jpg', ARRAY['dinde', 'volaille', 'nuggets', 'kfc', 'aile', 'cuisse', 'blanc']),
('radis', 'fruits_legumes', 'https://iqauznwytxtpslyflmvv.supabase.co/storage/v1/object/public/ingredient-images/radis.jpg', ARRAY['beurre', 'sel', 'rose', 'noir']),
('raisin', 'fruits_legumes', 'https://iqauznwytxtpslyflmvv.supabase.co/storage/v1/object/public/ingredient-images/raisins.jpg', ARRAY['vin', 'sec', 'grappe', 'blanc', 'noir']),
('riz', 'epicerie_salee', 'https://iqauznwytxtpslyflmvv.supabase.co/storage/v1/object/public/ingredient-images/riz.jpg', ARRAY['basmati', 'thai', 'risotto', 'oncle benz', 'cantonais', 'long', 'rond']),
('saumon', 'poissonnerie', 'https://iqauznwytxtpslyflmvv.supabase.co/storage/v1/object/public/ingredient-images/saumon.jpg', ARRAY['fume', 'pave', 'sushi', 'rose', 'gravlax']),
('tomate', 'fruits_legumes', 'https://iqauznwytxtpslyflmvv.supabase.co/storage/v1/object/public/ingredient-images/tomate.jpg', ARRAY['ketchup', 'sauce tomate', 'concentre', 'rouge', 'ronde', 'coeur de boeuf']),
('tomate cerise', 'fruits_legumes', 'https://iqauznwytxtpslyflmvv.supabase.co/storage/v1/object/public/ingredient-images/tomates-cerises.jpg', ARRAY['apero', 'grappe', 'petite', 'cocktail']),
('yaourt', 'produits_laitiers', 'https://iqauznwytxtpslyflmvv.supabase.co/storage/v1/object/public/ingredient-images/yaourt.jpg', ARRAY['dannette', 'mamie nova', 'yaourts', 'danettes']);